name: port-viewer
services:
  port-viewer:
    image: ghcr.io/sabbirislamgit/port-viewer:latest
    container_name: port-viewer
    hostname: port-viewer-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Asia/Dhaka
    ports:
      - "8585:8585"
    volumes:
      # Start/Stop docker section
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - port-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    
    # CasaOS Dashbaord Settings
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone for the container
      volumes:
        - container: /var/run/docker.sock
          description:
            en_US: Docker Socket (Required for Start/Stop actions)
      ports:
        - container: "8585"
          description:
            en_US: Web UI Access Port
      author: "Sabbir"
      category: "System Tools"
      icon: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/portainer.png"
      title:
        en_US: "Port Viewer"
      port_map: "8585"
      description:
        en_US: "Ultimate Docker container management and port scanning tool."

networks:
  port-network:
    name: port-network
    driver: bridge
